-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(50) NOT NULL,
    `lastName` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NULL,
    `phone` VARCHAR(15) NOT NULL,
    `dateOfBirth` DATETIME(3) NOT NULL,
    `gender` ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY') NOT NULL,
    `street` VARCHAR(255) NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL DEFAULT 'Tamil Nadu',
    `pincode` VARCHAR(6) NOT NULL,
    `occupation` VARCHAR(100) NULL,
    `organization` VARCHAR(100) NULL,
    `profileImage` TEXT NULL,
    `userType` ENUM('MEMBER', 'VOLUNTEER', 'ADMIN') NOT NULL DEFAULT 'MEMBER',
    `memberID` VARCHAR(20) NULL,
    `interests` JSON NULL,
    `howDidYouHear` VARCHAR(100) NULL,
    `emergencyContactName` VARCHAR(100) NULL,
    `emergencyContactPhone` VARCHAR(15) NULL,
    `subscribeNewsletter` BOOLEAN NOT NULL DEFAULT true,
    `isVerified` BOOLEAN NOT NULL DEFAULT false,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `verificationToken` VARCHAR(255) NULL,
    `resetPasswordToken` VARCHAR(255) NULL,
    `resetPasswordExpire` DATETIME(3) NULL,
    `googleId` VARCHAR(255) NULL,
    `lastLogin` DATETIME(3) NULL,
    `loginCount` INTEGER NOT NULL DEFAULT 0,
    `membershipDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    UNIQUE INDEX `users_memberID_key`(`memberID`),
    UNIQUE INDEX `users_googleId_key`(`googleId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
